// examples/web/src/features/swap/SwapPanel.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Amount } from "starkzap";
  import Card from "~/lib/ui/Card.svelte";
  import Text from "~/lib/ui/Text.svelte";
  import Button from "~/lib/ui/Button.svelte";
  import Select from "~/lib/ui/Select.svelte";
  import TextField from "~/lib/ui/TextField.svelte";
  import Segmented from "~/lib/ui/Segmented.svelte";
  import Toggle from "~/lib/ui/Toggle.svelte";
  import { tokens } from "~/lib/stores/tokens";
  import { sponsored, sponsoredAvailable } from "~/lib/stores/settings";
  import { PROVIDER_OPTIONS_LIST } from "~/lib/stores/wallet";
  import { balances, refresh } from "~/features/balances/store";
  import {
    tokenIn,
    tokenOut,
    amountIn,
    providerId,
    quote,
    quoting,
    submitting,
    error,
    dryRunning,
    dryRunResult,
    init,
    setTokenIn,
    setTokenOut,
    setAmountIn,
    setProvider,
    flip,
    fetchQuote,
    dryRun,
    swap,
  } from "./store";

  onMount(() => {
    init();
    void refresh();
  });

  // Debounced quote whenever the pair / amount / provider changes.
  $effect(() => {
    void [$tokenIn, $tokenOut, $amountIn, $providerId];
    const t = setTimeout(() => void fetchQuote(), 400);
    return () => clearTimeout(t);
  });

  const options = $derived(
    $tokens.map((t) => ({ label: t.symbol, value: t.address }))
  );
  const outTok = $derived($tokens.find((t) => t.address === $tokenOut));
  const inBalance = $derived(
    $balances.find((b) => b.token.address === $tokenIn)?.amount
  );
  const estOut = $derived(
    $quote && outTok
      ? Amount.fromRaw($quote.amountOutBase, outTok).toFormatted(true)
      : "—"
  );

  async function onSwap() {
    if (await swap()) void refresh();
  }
</script>

<Segmented
  options={PROVIDER_OPTIONS_LIST}
  value={$providerId}
  onchange={setProvider}
/>

<Card>
  <Text variant="label">You pay</Text>
  <Select
    options={options}
    value={$tokenIn}
    oninput={(e: Event) =>
      setTokenIn((e.currentTarget as HTMLSelectElement).value)}
  />
  <TextField
    label="Amount"
    placeholder="0.0"
    inputmode="decimal"
    value={$amountIn}
    oninput={(e: Event) =>
      setAmountIn((e.currentTarget as HTMLInputElement).value)}
  />
  <Text variant="muted">
    Balance: {inBalance ? inBalance.toFormatted(true) : "—"}
  </Text>

  <button class="flip" onclick={flip} aria-label="Flip tokens">⇅</button>

  <Text variant="label">You receive</Text>
  <Select
    options={options}
    value={$tokenOut}
    oninput={(e: Event) =>
      setTokenOut((e.currentTarget as HTMLSelectElement).value)}
  />
  <Text variant="body">{$quoting ? "Quoting…" : `≈ ${estOut}`}</Text>
  {#if $quote?.priceImpactBps != null}
    <Text variant="muted">
      Price impact: {(Number($quote.priceImpactBps) / 100).toFixed(2)}%{$quote.provider
        ? ` • ${$quote.provider}`
        : ""}
    </Text>
  {/if}
</Card>

{#if sponsoredAvailable}
  <Toggle label="Sponsored" bind:checked={$sponsored} />
{/if}
<Button
  title="Swap"
  loading={$submitting}
  disabled={!$quote || $quoting}
  onclick={onSwap}
/>
<Button
  variant="secondary"
  title="Dry run"
  loading={$dryRunning}
  disabled={!$amountIn.trim()}
  onclick={dryRun}
/>
{#if $dryRunResult}
  <Text variant="muted">{$dryRunResult.message}</Text>
{/if}
{#if $error}
  <Text variant="muted">{$error}</Text>
{/if}

<style>
  .flip {
    align-self: center;
    font-size: 20px;
    line-height: 1;
    padding: var(--sp-xs) var(--sp-sm);
    color: var(--accent);
    background: transparent;
    border: none;
    cursor: pointer;
  }
</style>

// examples/mobile/src/features/swap/SwapPanel.tsx
import { useEffect } from "react";
import { Pressable } from "react-native";
import { Amount } from "starkzap-native";
import {
  Card,
  Text,
  Button,
  TextField,
  Select,
  Segmented,
  IconSymbol,
  Toggle,
} from "@/ui";
import { useTheme } from "@/theme";
import { useTokensStore } from "@/core/tokens/store";
import { PROVIDER_OPTIONS_LIST } from "@/core/wallet/store";
import { useSettingsStore, useSponsoredAvailable } from "@/core/settings";
import { useBalancesStore } from "@/features/balances/store";
import { useSwapStore } from "@/features/swap/store";

export function SwapPanel() {
  const sponsoredAvailable = useSponsoredAvailable();
  const { sponsored, setSponsored } = useSettingsStore();
  const { colors, spacing } = useTheme();
  const tokens = useTokensStore((s) => s.tokens);
  const { balances, refresh } = useBalancesStore();
  const {
    tokenIn,
    tokenOut,
    amountIn,
    quote,
    quoting,
    submitting,
    error,
    providerId,
    dryRunning,
    dryRunResult,
    init,
    setTokenIn,
    setTokenOut,
    setAmountIn,
    setProvider,
    flip,
    fetchQuote,
    dryRun,
    swap,
  } = useSwapStore();

  useEffect(() => {
    if (tokens[0] && tokens[1]) init(tokens[0].address, tokens[1].address);
  }, [tokens, init]);

  useEffect(() => {
    const t = setTimeout(() => void fetchQuote(), 400);
    return () => clearTimeout(t);
  }, [tokenIn, tokenOut, amountIn, fetchQuote]);

  const options = tokens.map((t) => ({ label: t.symbol, value: t.address }));
  const outTok = tokens.find((t) => t.address === tokenOut);
  const inBalance = balances.find((b) => b.token.address === tokenIn)?.amount;
  const estOut =
    quote && outTok
      ? Amount.fromRaw(quote.amountOutBase, outTok).toFormatted(true)
      : "—";

  const onSwap = async () => {
    const ok = await swap();
    if (ok) {
      setAmountIn("");
      void refresh();
    }
  };

  return (
    <>
      <Segmented
        options={PROVIDER_OPTIONS_LIST}
        value={providerId}
        onChange={setProvider}
      />
      <Card>
        <Text variant="label">You pay</Text>
        <Select
          title="Select a token"
          options={options}
          value={tokenIn}
          onChange={setTokenIn}
        />
        <TextField
          label="Amount"
          placeholder="0.0"
          value={amountIn}
          onChangeText={setAmountIn}
          keyboardType="decimal-pad"
        />
        <Text variant="muted">
          Balance: {inBalance ? inBalance.toFormatted(true) : "—"}
        </Text>

        <Pressable
          onPress={flip}
          hitSlop={8}
          style={{ alignSelf: "center", padding: spacing.xs }}
        >
          <IconSymbol
            name="arrow.left.arrow.right"
            size={22}
            color={colors.primary}
          />
        </Pressable>

        <Text variant="label">You receive</Text>
        <Select
          title="Select a token"
          options={options}
          value={tokenOut}
          onChange={setTokenOut}
        />
        <Text variant="body">{quoting ? "Quoting…" : `≈ ${estOut}`}</Text>
        {quote?.priceImpactBps != null ? (
          <Text variant="muted">
            Price impact: {(Number(quote.priceImpactBps) / 100).toFixed(2)}%
            {quote.provider ? ` • ${quote.provider}` : ""}
          </Text>
        ) : null}
      </Card>

      {sponsoredAvailable ? (
        <Toggle
          label="Sponsored"
          value={sponsored}
          onValueChange={setSponsored}
        />
      ) : null}
      <Button
        title="Swap"
        loading={submitting}
        disabled={!quote || quoting}
        onPress={onSwap}
      />
      <Button
        title="Dry run"
        variant="secondary"
        loading={dryRunning}
        disabled={!amountIn.trim()}
        onPress={() => void dryRun()}
      />
      {dryRunResult ? (
        <Text
          style={{
            color: dryRunResult.ok ? colors.success : colors.danger,
          }}
        >
          {dryRunResult.message}
        </Text>
      ) : null}

      {error ? <Text style={{ color: colors.danger }}>{error}</Text> : null}
    </>
  );
}
