// examples/mobile/src/features/privacy/TongoPanel.tsx
import { useState } from "react";
import { Pressable } from "react-native";
import * as Clipboard from "expo-clipboard";
import { Amount } from "starkzap-native";
import { Card, Text, Button, TextField, Select } from "@/ui";
import { useWalletStore } from "@/core/wallet/store";
import { usePrivacyStore } from "@/features/privacy/store";
import { tongoTokens } from "@/features/privacy/tokens";

export default function TongoPanel() {
  const networkIndex = useWalletStore((s) => s.networkIndex);
  const {
    make,
    tokenSymbol,
    instance,
    token,
    connecting,
    busy,
    address,
    balance,
    pending,
    setToken,
    connect,
    fund,
    withdraw,
    transfer,
    rollover,
  } = usePrivacyStore();

  const [fundAmount, setFundAmount] = useState("");
  const [wAmount, setWAmount] = useState("");
  const [tAmount, setTAmount] = useState("");
  const [tx, setTx] = useState("");
  const [ty, setTy] = useState("");

  const tokenOptions = tongoTokens(networkIndex).map((t) => ({
    label: t.symbol,
    value: t.symbol,
  }));
  const fmt = (v: bigint) =>
    token
      ? Amount.fromRaw(v, token.decimals, token.symbol).toFormatted(true)
      : "—";

  if (!make) {
    return (
      <Card>
        <Text variant="subtitle">Private-key login required</Text>
        <Text variant="muted">
          Confidential balances are derived from your key, so this feature is
          available only when you sign in with a private key.
        </Text>
      </Card>
    );
  }

  return (
    <>
      <Card>
        <Text variant="label">Provider · Tongo</Text>
        <Text variant="label">Token</Text>
        <Select
          title="Select a token"
          options={tokenOptions}
          value={tokenSymbol}
          onChange={setToken}
        />
        <Button
          title={instance ? "Reconnect" : "Connect"}
          loading={connecting}
          disabled={!tokenSymbol}
          onPress={() => void connect()}
        />
      </Card>

      {instance ? (
        <>
          <Card>
            <Text variant="label">Confidential balance</Text>
            <Text variant="subtitle">{fmt(balance)}</Text>
            {pending > 0n ? (
              <>
                <Text variant="muted">Pending: {fmt(pending)}</Text>
                <Button
                  title="Rollover pending"
                  variant="secondary"
                  loading={busy}
                  onPress={() => void rollover()}
                />
              </>
            ) : null}
            <Pressable onPress={() => Clipboard.setStringAsync(address)}>
              <Text variant="muted">Your address (tap to copy)</Text>
              <Text variant="body">
                {address.slice(0, 10)}…{address.slice(-6)}
              </Text>
            </Pressable>
          </Card>

          <Card>
            <Text variant="label">Shield (deposit)</Text>
            <TextField
              label="Amount"
              placeholder="0.0"
              value={fundAmount}
              onChangeText={setFundAmount}
              keyboardType="decimal-pad"
            />
            <Button
              title="Shield"
              loading={busy}
              disabled={!fundAmount.trim()}
              onPress={() =>
                void fund(fundAmount).then(() => setFundAmount(""))
              }
            />
          </Card>

          <Card>
            <Text variant="label">Unshield (withdraw)</Text>
            <TextField
              label="Amount"
              placeholder="0.0"
              value={wAmount}
              onChangeText={setWAmount}
              keyboardType="decimal-pad"
            />
            <Text variant="muted">Unshields to your wallet address.</Text>
            <Button
              title="Unshield"
              loading={busy}
              disabled={!wAmount.trim()}
              onPress={() => void withdraw(wAmount)}
            />
          </Card>

          <Card>
            <Text variant="label">Private transfer</Text>
            <TextField
              label="Amount"
              placeholder="0.0"
              value={tAmount}
              onChangeText={setTAmount}
              keyboardType="decimal-pad"
            />
            <TextField
              label="Recipient x"
              placeholder="0x…"
              value={tx}
              onChangeText={setTx}
              autoCapitalize="none"
              autoCorrect={false}
            />
            <TextField
              label="Recipient y"
              placeholder="0x…"
              value={ty}
              onChangeText={setTy}
              autoCapitalize="none"
              autoCorrect={false}
            />
            <Button
              title="Send privately"
              loading={busy}
              disabled={!tAmount.trim() || !tx.trim() || !ty.trim()}
              onPress={() => void transfer(tAmount, tx, ty)}
            />
          </Card>
        </>
      ) : null}
    </>
  );
}

// examples/web/src/features/privacy/TongoPanel.svelte
<script lang="ts">
  import { Amount } from "starkzap";
  import Card from "~/lib/ui/Card.svelte";
  import Text from "~/lib/ui/Text.svelte";
  import Button from "~/lib/ui/Button.svelte";
  import Select from "~/lib/ui/Select.svelte";
  import TextField from "~/lib/ui/TextField.svelte";
  import { tongoTokens } from "./tokens";
  import {
    tokenSymbol,
    instance,
    token,
    connecting,
    busy,
    address,
    balance,
    pending,
    error,
    enabled,
    setToken,
    connect,
    refresh,
    fund,
    withdraw,
    transfer,
    rollover,
  } from "./store";

  let fundAmount = $state("");
  let withdrawAmount = $state("");
  let sendAmount = $state("");
  let sendKey = $state("");
  let copied = $state(false);

  async function copyKey() {
    await navigator.clipboard.writeText($address);
    copied = true;
    setTimeout(() => (copied = false), 1200);
  }

  const tokenOptions = $derived([
    { label: "Select a token", value: "" },
    ...$tongoTokens.map((t) => ({ label: t.symbol, value: t.symbol })),
  ]);
  const fmt = (base: bigint) =>
    $token ? Amount.fromRaw(base, $token.decimals, $token.symbol).toFormatted(true) : "—";

  async function onFund() {
    await fund(fundAmount);
    fundAmount = "";
  }
  async function onWithdraw() {
    await withdraw(withdrawAmount);
    withdrawAmount = "";
  }
  async function onSend() {
    await transfer(sendAmount, sendKey);
    sendAmount = "";
  }
</script>


{#if !$enabled}
  <Text variant="muted">
    Confidential balances require a private-key login (the capability is derived
    from your key at sign-in).
  </Text>
{:else}
  <Card>
    <Select
      label="Token"
      options={tokenOptions}
      value={$tokenSymbol}
      oninput={(e: Event) =>
        setToken((e.currentTarget as HTMLSelectElement).value)}
    />
    <Button
      title="Connect"
      loading={$connecting}
      disabled={!$tokenSymbol}
      onclick={connect}
    />
    {#if $error}<Text variant="muted">{$error}</Text>{/if}
  </Card>

  {#if $instance}
    <Card>
      <Text variant="subtitle">Confidential {$token?.symbol}</Text>
      <Text variant="muted">Balance: {fmt($balance)}</Text>
      <Text variant="muted">Pending: {fmt($pending)}</Text>
      {#if $address}
        <Text variant="label">Public key (share to receive)</Text>
        <button class="pubkey" onclick={copyKey}>{$address}</button>
        <Text variant="muted">{copied ? "Copied!" : "Tap to copy"}</Text>
      {/if}
      <Button variant="secondary" title="Refresh" onclick={refresh} />
    </Card>

    <Card>
      <Text variant="subtitle">Shield (deposit)</Text>
      <TextField label="Amount" placeholder="0.0" inputmode="decimal" bind:value={fundAmount} />
      <Button title="Shield" loading={$busy} disabled={!fundAmount.trim()} onclick={onFund} />
    </Card>

    <Card>
      <Text variant="subtitle">Private send</Text>
      <TextField label="Amount" placeholder="0.0" inputmode="decimal" bind:value={sendAmount} />
      <TextField
        label="Recipient public key"
        placeholder="Tongo public key…"
        bind:value={sendKey}
      />
      <Button
        title="Send privately"
        loading={$busy}
        disabled={!sendAmount.trim() || !sendKey.trim()}
        onclick={onSend}
      />
    </Card>

    <Card>
      <Text variant="subtitle">Unshield (withdraw)</Text>
      <TextField label="Amount" placeholder="0.0" inputmode="decimal" bind:value={withdrawAmount} />
      <Text variant="muted">Unshields to your wallet address.</Text>
      <Button
        title="Unshield"
        loading={$busy}
        disabled={!withdrawAmount.trim()}
        onclick={onWithdraw}
      />
      <Button variant="ghost" title="Rollover pending" loading={$busy} onclick={rollover} />
    </Card>
  {/if}
{/if}

<style>
  .pubkey {
    text-align: left;
    font-family: var(--font-mono);
    font-size: 13px;
    color: var(--text);
    background: transparent;
    border: none;
    padding: 0;
    cursor: pointer;
    word-break: break-all;
  }
</style>
