// examples/mobile-new/src/ui/Segmented.tsx
import { View, Pressable, StyleSheet } from "react-native";
import { useTheme } from "@/theme";
import { Text } from "./Text";

export interface SegmentedOption<T extends string> {
  label: string;
  value: T;
}

export function Segmented<T extends string>({
  options,
  value,
  onChange,
}: {
  options: SegmentedOption<T>[];
  value: T;
  onChange: (value: T) => void;
}) {
  const { colors, radius } = useTheme();
  return (
    <View
      style={[
        styles.row,
        { borderColor: colors.border, borderRadius: radius.md },
      ]}
    >
      {options.map((opt) => {
        const active = opt.value === value;
        return (
          <Pressable
            key={opt.value}
            onPress={() => onChange(opt.value)}
            style={[
              styles.pill,
              { borderRadius: radius.sm },
              active && { backgroundColor: colors.primary },
            ]}
          >
            <Text
              style={[
                styles.text,
                { color: active ? colors.primaryText : colors.textMuted },
              ]}
            >
              {opt.label}
            </Text>
          </Pressable>
        );
      })}
    </View>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: "row", borderWidth: 1, padding: 3, gap: 3 },
  pill: { flex: 1, paddingVertical: 8, alignItems: "center" },
  text: { fontSize: 13, fontWeight: "600" },
});

// examples/web/src/lib/ui/Segmented.svelte
<script lang="ts">
  export interface SegmentedOption {
    label: string;
    value: string;
  }

  let {
    options,
    value = $bindable(""),
    onchange,
  }: {
    options: SegmentedOption[];
    value?: string;
    onchange?: (value: string) => void;
  } = $props();

  function select(v: string) {
    value = v;
    onchange?.(v);
  }
</script>

<div class="row">
  {#each options as opt (opt.value)}
    <button class:active={opt.value === value} onclick={() => select(opt.value)}>
      {opt.label}
    </button>
  {/each}
</div>

<style>
  .row {
    display: flex;
    gap: 3px;
    padding: 3px;
    border: 1px solid var(--border);
    border-radius: var(--r-md);
  }
  button {
    flex: 1;
    padding: 8px 0;
    font-size: 13px;
    font-weight: 600;
    color: var(--text-muted);
    background: transparent;
    border: none;
    border-radius: var(--r-sm);
    cursor: pointer;
  }
  .active {
    background: var(--primary);
    color: var(--primary-text);
  }
</style>
