// examples/mobile/src/ui/Text.tsx
import { Text as RNText, type TextProps, StyleSheet } from "react-native";
import { useTheme } from "@/theme";

type Variant = "title" | "subtitle" | "body" | "label" | "muted";

export function Text({
  variant = "body",
  style,
  ...props
}: TextProps & { variant?: Variant }) {
  const { colors } = useTheme();
  const muted = variant === "muted" || variant === "label";
  return (
    <RNText
      {...props}
      style={[
        styles[variant],
        { color: muted ? colors.textMuted : colors.text },
        style,
      ]}
    />
  );
}

const styles = StyleSheet.create({
  title: { fontSize: 26, fontWeight: "700", letterSpacing: -0.3 },
  subtitle: { fontSize: 16, fontWeight: "600" },
  body: { fontSize: 15 },
  label: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  muted: { fontSize: 13 },
});

// examples/web/src/lib/ui/Text.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  type Variant = "title" | "subtitle" | "body" | "label" | "muted";
  let {
    variant = "body",
    children,
  }: { variant?: Variant; children: Snippet } = $props();
</script>

<span class={variant}>{@render children()}</span>

<style>
  span {
    display: block;
    color: var(--text);
  }
  .title {
    font-size: 26px;
    font-weight: 700;
    letter-spacing: -0.3px;
  }
  .subtitle {
    font-size: 16px;
    font-weight: 600;
  }
  .body {
    font-size: 15px;
  }
  .label {
    font-size: 12px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-muted);
  }
  .muted {
    font-size: 13px;
    color: var(--text-muted);
  }
</style>
